Makefile
cuallee/__init__.py
test/test_numeric_rules.py

Implement computing and data frame from result display. 
Bug with tuples of column to fix.

Feature compute

---

cuallee/__init__.py
test/test_numeric_rules.py

Implement code to check if the value passed in the function are strings or numerical

fix tests for is_contained_in

---

cuallee/__init__.py
test/test_is_between.py

- Added validation to check `is_between` 
- New test cases.

Added the is_between files

---

cuallee/__init__.py
test/test_contained_in.py
test/test_numeric_rules.py

-Move tests for contained_in to a new file test
- Add code to change list to tuple if user pass values as list

Feature contained in test cases

---

cuallee/__init__.py

- Add the column observation date in the final data frame

add col observation_date to final dataframe

---

cuallee/snowpark_validation.py
requirements.txt
test/unit/snowpark_dataframe/test_is_between.py
test/unit/snowpark_dataframe/test_is_complete.py
test/unit/snowpark_dataframe/test_is_contained_in.py
test/unit/snowpark_dataframe/test_is_daily.py
test/unit/snowpark_dataframe/test_is_equal_than.py
test/unit/snowpark_dataframe/test_is_greater_or_equal_than.py
test/unit/snowpark_dataframe/test_is_greater_than.py
test/unit/snowpark_dataframe/test_is_in_billions.py
test/unit/snowpark_dataframe/test_is_in_millions.py
test/unit/snowpark_dataframe/test_is_inside_interquartile_range.py
test/unit/snowpark_dataframe/test_is_less_or_equal_than.py
test/unit/snowpark_dataframe/test_is_less_than.py
test/unit/snowpark_dataframe/test_is_negative.py
test/unit/snowpark_dataframe/test_is_on_friday.py
test/unit/snowpark_dataframe/test_is_on_monday.py
test/unit/snowpark_dataframe/test_is_on_saturday.py
test/unit/snowpark_dataframe/test_is_on_schedule.py
test/unit/snowpark_dataframe/test_is_on_sunday.py
test/unit/snowpark_dataframe/test_is_on_thursday.py
test/unit/snowpark_dataframe/test_is_on_tuesday.py
test/unit/snowpark_dataframe/test_is_on_wednesday.py
test/unit/snowpark_dataframe/test_is_on_weekday.py
test/unit/snowpark_dataframe/test_is_on_weekend.py
test/unit/snowpark_dataframe/test_is_positive.py
test/unit/snowpark_dataframe/test_is_unique.py
test/unit/snowpark_dataframe/test_name_columns.py
test/unit/snowpark_dataframe/test_satisfies.py

Feature test snow 5

---

test/unit/pyspark_dataframe/test_are_complete.py
test/unit/pyspark_dataframe/test_are_unique.py
test/unit/pyspark_dataframe/test_has_correlation.py
test/unit/pyspark_dataframe/test_has_entropy.py
test/unit/pyspark_dataframe/test_has_max.py
test/unit/pyspark_dataframe/test_has_max_by.py
test/unit/pyspark_dataframe/test_has_mean.py
test/unit/pyspark_dataframe/test_has_min.py
test/unit/pyspark_dataframe/test_has_min_by.py
test/unit/pyspark_dataframe/test_has_pattern.py
test/unit/pyspark_dataframe/test_has_std.py
test/unit/pyspark_dataframe/test_has_sum.py
test/unit/pyspark_dataframe/test_has_workflow.py
test/unit/pyspark_dataframe/test_name_columns.py
test/unit/snowpark_dataframe/test_are_complete.py
test/unit/snowpark_dataframe/test_has_pattern.py
test/unit/snowpark_dataframe/test_name_columns.py

Feature pyspark test 2

---

test/unit/pyspark_dataframe/test_is_between.py
test/unit/pyspark_dataframe/test_is_complete.py
test/unit/pyspark_dataframe/test_is_contained_in.py
test/unit/pyspark_dataframe/test_is_equal_than.py
test/unit/pyspark_dataframe/test_is_greater_or_equal_than.py
test/unit/pyspark_dataframe/test_is_greater_than.py
test/unit/pyspark_dataframe/test_is_in_billions.py
test/unit/pyspark_dataframe/test_is_in_millions.py
test/unit/pyspark_dataframe/test_is_inside_interquartile_range.py
test/unit/pyspark_dataframe/test_is_less_or_equal_than.py
test/unit/pyspark_dataframe/test_is_less_than.py
test/unit/pyspark_dataframe/test_is_negative.py
test/unit/pyspark_dataframe/test_is_positive.py
test/unit/pyspark_dataframe/test_is_unique.py
test/unit/pyspark_dataframe/test_satisfies.py

Feature pyspark test 3

---

cuallee/duckdb_validation.py
pyproject.toml
test/unit/duckdb_dataframe/test_is_daily.py

Added fixes for duckdb

---

.github/workflows/ci.yml
Makefile
README.md

Feature docs upgrade

---

.github/workflows/ci.yml

Addition of new configuration for v3 action

---

.github/workflows/ci.yml
pyproject.toml
setup.cfg

Feature upgrade umbrella

---

test/unit/iso_checks/test_countries.py
test/unit/iso_checks/test_currencies.py

Added new iso tests

---

pyproject.toml
setup.cfg

Added bump version and downgraded pandas

---

pyproject.toml
setup.cfg

Bump version

---

.github/workflows/ci.yml

Added polars install on ci

---

.github/workflows/ci.yml

Added environment variable to ci/cd github action

---

.github/workflows/ci.yml
conftest.py

Added auth action to ci/cd

---

.github/workflows/ci.yml
.gitignore
conftest.py
pyproject.toml

Addition of pyarrow dependency for bigquery

---

cuallee/pyspark_validation.py
pyproject.toml
setup.cfg
test/unit/pyspark_dataframe/test_is_unique.py

Feature fix is unique

---

cuallee/polars_validation.py
pyproject.toml
setup.cfg

Bump to 0.4.7 and fix polars

---

cuallee/pyspark_validation.py
pyproject.toml
setup.cfg
test/unit/pyspark_dataframe/test_are_complete.py

Addition of fix for are complete

---

conftest.py
cuallee/bigquery_validation.py
test/unit/bigquery/test_are_complete.py
test/unit/bigquery/test_is_complete.py

Feature bigquery r complete

---

conftest.py
cuallee/bigquery_validation.py
test/unit/bigquery/test_are_complete.py
test/unit/bigquery/test_is_complete.py
test/unit/bigquery/test_is_unique.py

Feature bq is unique

---

cuallee/bigquery_validation.py
test/unit/bigquery/test_are_unique.py

implement bq are_unique

---

README.md
cuallee/__init__.py
pyproject.toml
setup.cfg

Feature t minus check

---

README.md
cuallee/__init__.py
pyproject.toml
setup.cfg
test/unit/pyspark_dataframe/test_is_t_minus_n.py

Feature add test tminus

---

cuallee/bigquery_validation.py
pyproject.toml
setup.cfg

Added quoting to bigquery validation

---

cuallee/bigquery_validation.py
test/unit/bigquery/test_is_contained_in.py

Feature bq iscontainedin

---

cuallee/bigquery_validation.py
test/unit/bigquery/test_is_complete.py
test/unit/bigquery/test_is_contained_in.py
test/unit/bigquery/test_is_daily.py
test/unit/bigquery/test_is_unique.py

Feature bq isdaily

---

pyproject.toml

Fix version to 0.8.1 in pipeline

---

pyproject.toml

revert version snow

---

README.md
cuallee/__init__.py
pyproject.toml
setup.cfg
test/unit/pyspark_dataframe/test_has_pattern.py

Added is legit check for validating empty strings

---

cuallee/__init__.py
pyproject.toml
setup.cfg
test/unit/duckdb_dataframe/test_has_pattern.py
test/unit/pandas_dataframe/test_has_pattern.py
test/unit/polars_dataframe/test_has_pattern.py
test/unit/pyspark_dataframe/test_are_unique.py
test/unit/pyspark_dataframe/test_is_unique.py

Feature is pk

---

cuallee/polars_validation.py
test/unit/polars_dataframe/test_has_workflow.py

Added last workflow validation

---

cuallee/__init__.py
cuallee/dagster/__init__.py
cuallee/polars_validation.py
pyproject.toml
setup.cfg

Feature dagster checks

---

cuallee/__init__.py
cuallee/polars_validation.py
pyproject.toml
setup.cfg
test/unit/class_control/test_methods.py
test/unit/polars_dataframe/test_is_daily.py

Feature control checks

---

.github/workflows/ci.yml
README.md
cuallee/dagster/__init__.py
pyproject.toml
setup.cfg
test/unit/dagster_checks/test_methods.py

Feature snowflake upgrade

---

cuallee/duckdb_validation.py
pyproject.toml
setup.cfg

upgraded duckdb

---

cuallee/pandas_validation.py
pyproject.toml
setup.cfg

Modified pandas has pattern to fill nulls

---

README.md

Added loc and cuallee logo to the right

---

cuallee/__init__.py
cuallee/snowpark_validation.py
pyproject.toml
setup.cfg

Feature snowpark session

---

README.md
cuallee/__init__.py
pyproject.toml
setup.cfg
test/unit/class_control/test_methods.py

Feature fillness

---

README.md
cuallee/__init__.py
pyproject.toml
setup.cfg
test/unit/bigquery/test_are_complete.py
test/unit/bigquery/test_are_unique.py
test/unit/bigquery/test_is_complete.py
test/unit/bigquery/test_is_contained_in.py
test/unit/bigquery/test_is_daily.py
test/unit/bigquery/test_is_unique.py
test/unit/bigquery/test_not_contained_in.py
test/unit/class_control/test_methods.py

Feature fix bq test

---

cuallee/__init__.py
cuallee/pyspark_validation.py
pyproject.toml
setup.cfg

Feature pyspark hotfix

---

.github/workflows/ci.yml
cuallee/__init__.py
pyproject.toml

Feature req req

---

paper/paper.md

a few last edits

---

.github/workflows/ci.yml
cuallee/__init__.py
cuallee/bigquery_validation.py
cuallee/cloud/__init__.py
cuallee/duckdb_validation.py
cuallee/pandas_validation.py
cuallee/polars_validation.py
cuallee/pyspark_validation.py
cuallee/report/__init__.py
cuallee/snowpark_validation.py
pyproject.toml
setup.cfg
test/unit/bigquery/test_is_daily.py
test/unit/class_control/test_methods.py
test/unit/cloud/test_publish.py
test/unit/duckdb_dataframe/test_has_infogain.py
test/unit/polars_dataframe/test_has_infogain.py
test/unit/pyspark_dataframe/test_has_infogain.py

Feature intelligence

---

README.md
cuallee/__init__.py
cuallee/report/__init__.py
pyproject.toml

Feature fix bigdf fail

---

README.md
cuallee/__init__.py
cuallee/pyspark_validation.py
pyproject.toml
setup.cfg
test/unit/class_control/test_methods.py

Added spark connect implementation

---

cuallee/__init__.py
pyproject.toml
setup.cfg

Added new version deprecation polars sorted

---

cuallee/__init__.py
cuallee/duckdb_validation.py
pyproject.toml
setup.cfg

Bump duckdb and fixed teste cases

---

README.md

---
- #213 
- https://github.com/openjournals/joss-reviews/issues/6684

[JOSS REVIEW] 🔗Add link to Community guidelines (Fix #213)

---

README.md

Bumped version and added README reference to documentation

---

README.md

Removed compatibility with older versions of DuckDB

---

test/performance/soda/test_performance_soda.py
test/unit/class_rule/test_rule_update_functions.py

Amended the key signature as new options made the unique value change

---

paper/paper.bib
paper/paper.md

Due to the Joss submission
https://github.com/openjournals/joss-reviews/issues/6684

minor changes

---

paper/paper.bib
paper/paper.md

Due to the JOSS submission: 
https://github.com/openjournals/joss-reviews/issues/6684

minor changes 

---

pyproject.toml
setup.cfg
test/unit/bigquery/test_is_complete.py

Added fixes and release notes

---

test/unit/bigquery/test_is_daily.py
test/unit/bigquery/test_not_contained_in.py

Fix numpy issues

---

test/unit/bigquery/test_is_daily.py
test/unit/bigquery/test_is_unique.py
test/unit/bigquery/test_not_contained_in.py

Removal of the BQ assertions temporarily

---

test/unit/daft/test_is_daily.py

Added daft validations

---

pyproject.toml
setup.cfg

Release for archive v0.11.0

---

cuallee/__init__.py
cuallee/dagster/__init__.py
cuallee/pyspark_validation.py
pyproject.toml
setup.cfg
test/unit/dagster_checks/test_methods.py
test/unit/pyspark_dataframe/test_is_custom.py

Feature dagster check results

---

README.md
cuallee/polars_validation.py
pyproject.toml
test/unit/polars_dataframe/test_has_mean.py

Feature polars one

---

README.md
cuallee/dagster/__init__.py
cuallee/polars_validation.py
pyproject.toml
setup.cfg
test/unit/polars_dataframe/test_has_mean.py

Feature dagster utils

---

cuallee/__init__.py
cuallee/bio/amino_acids.csv
cuallee/bio/checks.py
cuallee/logic/__init__.py
pyproject.toml
setup.cfg
test/unit/dagster_checks/test_methods.py

Feature bio checks

---

MANIFEST.in

add manifest to include csv bio file in package

---

.gitignore
cuallee/__init__.py
pyproject.toml
setup.cfg

Feature fix manifest

---

cuallee/polars_validation.py

change all values to str in return dataframe for polars

---

cuallee/__init__.py
pyproject.toml
setup.cfg

Added new version for polars fix

---

cuallee/__init__.py
cuallee/bigquery_validation.py
cuallee/bio/checks.py
cuallee/daft_validation.py
cuallee/duckdb_validation.py
cuallee/iso/checks.py
cuallee/pandas_validation.py
cuallee/polars_validation.py
cuallee/pyspark_validation.py
cuallee/snowpark_validation.py
pyproject.toml
setup.cfg

Feature rule rename

---

README.md
cuallee/__init__.py
cuallee/bio/checks.py
cuallee/duckdb_validation.py
cuallee/pyspark_validation.py
test/unit/bio_checks/test_duckdb.py
test/unit/bio_checks/test_polars.py
test/unit/bio_checks/test_pyspark.py

Feature add biochecks

---

README.md
cuallee/cloud/__init__.py

Added logos for static image display

---

cuallee/__init__.py
cuallee/polars_validation.py
pyproject.toml
setup.cfg
test/unit/polars_dataframe/test_is_unique.py

Feature polars ignore nulls

---

cuallee/__init__.py

In docstrings & variable
- [] pyspark
- [] snowpark
- [] pandas
- [] duckdb
- [] polars

Correct spelling

---

cuallee/__init__.py
pyproject.toml
test/unit/pyspark_dataframe/test_spark_validation.py

Feature bump tools

---

cuallee/__init__.py
pyproject.toml
setup.cfg
test/unit/pyspark_dataframe/test_spark_validation.py

Feature tag 0132

---

README.md
cuallee/__init__.py
cuallee/cloud/__init__.py
cuallee/pyspark_validation.py
pyproject.toml
setup.cfg
test/unit/cloud/test_publish.py

Feature dtype

---

cuallee/__init__.py
pyproject.toml
setup.cfg

Added proper versions to support new syntax

---

cuallee/polars_validation.py
test/unit/class_check/test_ok.py

Feature test increase ok method on check

---

.gitignore
test/unit/snowpark_dataframe/test_is_inside_interquartile_range.py

New values for IQR test

---

cuallee/pandas_validation.py
test/unit/pandas_dataframe/test_is_custom.py

Adds pandas is_custom()

---

cuallee/family/datetime/__init__.py
cuallee/family/generic/__init__.py
cuallee/family/numeric/__init__.py

Feature cleaning families

---

cuallee/engine/pyspark/predicates/generic.py
cuallee/family/generic/__init__.py

Feature pyspark generic

---

.gitignore
README.md
pyproject.toml
test/unit/pyspark_dataframe/test_satisfies.py
test/unit/pyspark_dataframe/test_spark_validation.py

Added support for pyspark4.0
